[package]
edition = "2018"
name = "egg-simpl"
version = "0.0.1"

[lib]
name = "egg_simpl"
crate-type = ["staticlib"]

[dependencies]
egg = "0.9.3"
ordered-float = "3.7"
once_cell = "1.17.1"

[features]
count = []
